// Command generate-api discovers resource modules and produces the bundled
// OpenAPI contract plus the Go registration list consumed by the API runtime.
package main

import (
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"go.yaml.in/yaml/v3"
)

var (
	goNamePattern = regexp.MustCompile(`^[A-Z][A-Za-z0-9]*$`)
	pluralPattern = regexp.MustCompile(`^[a-z0-9](?:[-a-z0-9]*[a-z0-9])?$`)
)

type resourceMetadata struct {
	APIVersion string   `yaml:"api-version"`
	PathPrefix string   `yaml:"path-prefix"`
	Kind       string   `yaml:"kind"`
	Plural     string   `yaml:"plural"`
	SpecSchema string   `yaml:"spec-schema"`
	Operations []string `yaml:"operations"`
}

type resourceModule struct {
	Metadata resourceMetadata
	Schemas  map[string]any
}

func main() {
	basePath := flag.String("base", "openapi.yaml", "base OpenAPI document")
	resourcesDir := flag.String("resources", "resources", "resource module directory")
	specOutput := flag.String("spec-output", "openapi.bundle.yaml", "generated bundled OpenAPI document")
	registryOutput := flag.String("registry-output", "resource_registry.gen.go", "generated Go resource registry")
	modelsImport := flag.String("models-import", "", "Go import path containing generated OpenAPI models")
	resourceImport := flag.String("resource-import", "", "Go import path containing the generic resource model")
	flag.Parse()
	if *modelsImport == "" {
		fail("models-import is required")
	}
	if *resourceImport == "" {
		fail("resource-import is required")
	}

	base := readYAMLMap(*basePath)
	modules := readModules(*resourcesDir)
	for _, module := range modules {
		addResource(base, module)
	}
	base["x-stigmergy-file-purpose"] = "Generated, self-contained OpenAPI document used for code generation, validation, Swagger UI, and /openapi.json."

	encoded, err := json.MarshalIndent(base, "", "  ")
	if err != nil {
		fail("encode generated OpenAPI document: %v", err)
	}
	loader := openapi3.NewLoader()
	document, err := loader.LoadFromData(encoded)
	if err != nil {
		fail("load generated OpenAPI document: %v", err)
	}
	if err := document.Validate(context.Background()); err != nil {
		fail("validate generated OpenAPI document: %v", err)
	}
	bundled, err := yaml.Marshal(base)
	if err != nil {
		fail("encode generated OpenAPI YAML: %v", err)
	}
	bundled = append([]byte("# Code generated by generate-api; DO NOT EDIT.\n# This self-contained contract drives code generation, request validation, Swagger UI, and /openapi.json.\n"), bundled...)
	writeFile(*specOutput, bundled)
	writeRegistry(*registryOutput, *modelsImport, *resourceImport, modules)
}

func readModules(directory string) []resourceModule {
	paths, err := filepath.Glob(filepath.Join(directory, "*.yaml"))
	if err != nil {
		fail("find resource modules: %v", err)
	}
	if len(paths) == 0 {
		fail("no resource modules found in %s", directory)
	}
	slices.Sort(paths)
	modules := make([]resourceModule, 0, len(paths))
	seenKinds := make(map[string]struct{})
	seenPaths := make(map[string]struct{})
	for _, path := range paths {
		document := readYAMLMap(path)
		metadataValue, found := document["x-stigmergy-resource"]
		if !found {
			fail("%s: x-stigmergy-resource is required", path)
		}
		metadataBytes, err := yaml.Marshal(metadataValue)
		if err != nil {
			fail("%s: encode resource metadata: %v", path, err)
		}
		var metadata resourceMetadata
		if err := yaml.Unmarshal(metadataBytes, &metadata); err != nil {
			fail("%s: decode resource metadata: %v", path, err)
		}
		validateMetadata(path, metadata)
		if _, found := seenKinds[metadata.Kind]; found {
			fail("%s: duplicate resource kind %q", path, metadata.Kind)
		}
		collectionPath := strings.TrimRight(metadata.PathPrefix, "/") + "/" + metadata.Plural
		if _, found := seenPaths[collectionPath]; found {
			fail("%s: duplicate collection path %q", path, collectionPath)
		}
		seenKinds[metadata.Kind] = struct{}{}
		seenPaths[collectionPath] = struct{}{}
		delete(document, "x-stigmergy-resource")
		if _, found := document[metadata.SpecSchema]; !found {
			fail("%s: spec schema %q is not defined", path, metadata.SpecSchema)
		}
		for name, schema := range document {
			if !goNamePattern.MatchString(name) {
				fail("%s: schema name %q must be a Go-style exported identifier", path, name)
			}
			document[name] = rewriteLocalRefs(schema)
		}
		modules = append(modules, resourceModule{Metadata: metadata, Schemas: document})
	}
	return modules
}

func validateMetadata(path string, metadata resourceMetadata) {
	if metadata.APIVersion == "" || metadata.PathPrefix == "" || metadata.Kind == "" || metadata.Plural == "" || metadata.SpecSchema == "" {
		fail("%s: api-version, path-prefix, kind, plural, and spec-schema are required", path)
	}
	if !strings.HasPrefix(metadata.PathPrefix, "/") || strings.HasSuffix(metadata.PathPrefix, "/") {
		fail("%s: path-prefix must start with and not end with '/'", path)
	}
	if !goNamePattern.MatchString(metadata.Kind) || !goNamePattern.MatchString(metadata.SpecSchema) {
		fail("%s: kind and spec-schema must be Go-style exported identifiers", path)
	}
	if !pluralPattern.MatchString(metadata.Plural) {
		fail("%s: plural must be a lowercase kebab-case path segment", path)
	}
	if len(metadata.Operations) == 0 {
		fail("%s: at least one operation is required", path)
	}
	allowed := map[string]bool{"create": true, "list": true, "get": true, "put": true, "delete": true, "delete-collection": true}
	seen := make(map[string]bool)
	for _, operation := range metadata.Operations {
		if !allowed[operation] {
			fail("%s: unsupported operation %q", path, operation)
		}
		if seen[operation] {
			fail("%s: duplicate operation %q", path, operation)
		}
		seen[operation] = true
	}
}

func addResource(root map[string]any, module resourceModule) {
	metadata := module.Metadata
	paths := requiredMap(root, "paths")
	components := requiredMap(root, "components")
	schemas := requiredMap(components, "schemas")
	for name, schema := range module.Schemas {
		if _, found := schemas[name]; found {
			fail("resource %s: duplicate schema %q", metadata.Kind, name)
		}
		schemas[name] = schema
	}

	createName := metadata.Kind + "Create"
	listName := metadata.Kind + "List"
	schemas[createName] = envelopeSchema(metadata, metadata.SpecSchema, false)
	schemas[metadata.Kind] = envelopeSchema(metadata, metadata.SpecSchema, false)
	schemas[listName] = listSchema(metadata)

	tags, _ := root["tags"].([]any)
	root["tags"] = append(tags, map[string]any{"name": metadata.Kind + "s"})
	collectionPath := strings.TrimRight(metadata.PathPrefix, "/") + "/" + metadata.Plural
	itemPath := collectionPath + "/{name}"
	collection := map[string]any{}
	item := map[string]any{}
	operations := operationSet(metadata.Operations)
	if operations["list"] {
		collection["get"] = listOperation(metadata)
	}
	if operations["create"] {
		collection["post"] = createOperation(metadata)
	}
	if operations["delete-collection"] {
		collection["delete"] = deleteCollectionOperation(metadata)
	}
	if operations["get"] {
		item["get"] = getOperation(metadata)
	}
	if operations["put"] {
		item["put"] = putOperation(metadata)
	}
	if operations["delete"] {
		item["delete"] = deleteOperation(metadata)
	}
	if len(item) > 0 {
		item["parameters"] = []any{nameParameter()}
	}
	if len(collection) > 0 {
		paths[collectionPath] = collection
	}
	if len(item) > 0 {
		paths[itemPath] = item
	}
}

func envelopeSchema(metadata resourceMetadata, specSchema string, _ bool) map[string]any {
	return map[string]any{
		"type":                 "object",
		"additionalProperties": false,
		"required":             []any{"apiVersion", "kind", "metadata", "spec"},
		"properties": map[string]any{
			"apiVersion": map[string]any{"type": "string", "const": metadata.APIVersion},
			"kind":       map[string]any{"type": "string", "const": metadata.Kind},
			"metadata":   schemaRef("Metadata"),
			"spec":       schemaRef(specSchema),
		},
	}
}

func listSchema(metadata resourceMetadata) map[string]any {
	return map[string]any{
		"type":                 "object",
		"additionalProperties": false,
		"required":             []any{"apiVersion", "kind", "metadata", "items"},
		"properties": map[string]any{
			"apiVersion": map[string]any{"type": "string", "const": metadata.APIVersion},
			"kind":       map[string]any{"type": "string", "const": metadata.Kind + "List"},
			"metadata":   schemaRef("ListMetadata"),
			"items": map[string]any{
				"type":  "array",
				"items": schemaRef(metadata.Kind),
			},
		},
	}
}

func listOperation(metadata resourceMetadata) map[string]any {
	return map[string]any{
		"tags":        []any{metadata.Kind + "s"},
		"summary":     "List " + metadata.Kind + " resources",
		"operationId": "list" + metadata.Kind + "s",
		"responses": map[string]any{
			"200": map[string]any{
				"description": "Resource list at one storage revision",
				"headers": map[string]any{
					"X-Resource-Version": resourceVersionHeader(),
				},
				"content": jsonContent(schemaRef(metadata.Kind + "List")),
			},
			"500": errorResponse("Resource store request failed"),
		},
	}
}

func createOperation(metadata resourceMetadata) map[string]any {
	return map[string]any{
		"tags":        []any{metadata.Kind + "s"},
		"summary":     "Create a " + metadata.Kind,
		"operationId": "create" + metadata.Kind,
		"requestBody": map[string]any{"required": true, "content": jsonContent(schemaRef(metadata.Kind + "Create"))},
		"responses": map[string]any{
			"201": resourceResponse(metadata.Kind, true),
			"400": errorResponse("Request does not match the resource schema"),
			"409": errorResponse("Resource already exists"),
			"422": errorResponse("Resource is invalid"),
			"500": errorResponse("Resource store request failed"),
		},
	}
}

func getOperation(metadata resourceMetadata) map[string]any {
	return map[string]any{
		"tags":        []any{metadata.Kind + "s"},
		"summary":     "Get one " + metadata.Kind,
		"operationId": "get" + metadata.Kind,
		"responses": map[string]any{
			"200": resourceResponse(metadata.Kind, false),
			"400": errorResponse("Resource name is invalid"),
			"404": errorResponse("Resource not found"),
			"500": errorResponse("Resource store request failed"),
		},
	}
}

func putOperation(metadata resourceMetadata) map[string]any {
	return map[string]any{
		"tags":        []any{metadata.Kind + "s"},
		"summary":     "Create or replace one " + metadata.Kind,
		"description": "Idempotently stores the latest resource state.",
		"operationId": "put" + metadata.Kind,
		"requestBody": map[string]any{"required": true, "content": jsonContent(schemaRef(metadata.SpecSchema))},
		"responses": map[string]any{
			"200": resourceResponse(metadata.Kind, false),
			"201": resourceResponse(metadata.Kind, true),
			"400": errorResponse("Request does not match the resource schema"),
			"409": errorResponse("Concurrent resource update"),
			"422": errorResponse("Resource is invalid"),
			"500": errorResponse("Resource store request failed"),
		},
	}
}

func deleteOperation(metadata resourceMetadata) map[string]any {
	return map[string]any{
		"tags":        []any{metadata.Kind + "s"},
		"summary":     "Delete one " + metadata.Kind,
		"operationId": "delete" + metadata.Kind,
		"parameters":  []any{ifMatchParameter()},
		"responses": map[string]any{
			"204": map[string]any{"description": "Resource deleted"},
			"400": errorResponse("Resource name is invalid"),
			"404": errorResponse("Resource not found"),
			"409": errorResponse("Resource version conflict"),
			"428": errorResponse("If-Match is required"),
			"500": errorResponse("Resource store request failed"),
		},
	}
}

func deleteCollectionOperation(metadata resourceMetadata) map[string]any {
	return map[string]any{
		"tags":        []any{metadata.Kind + "s"},
		"summary":     "Delete all " + metadata.Kind + " resources",
		"operationId": "delete" + metadata.Kind + "s",
		"responses": map[string]any{
			"200": map[string]any{
				"description": "Resources deleted",
				"content":     jsonContent(schemaRef("DeleteCollectionResult")),
			},
			"500": errorResponse("Resource store request failed"),
		},
	}
}

func resourceResponse(schema string, includeLocation bool) map[string]any {
	headers := map[string]any{"ETag": etagHeader()}
	if includeLocation {
		headers["Location"] = map[string]any{"description": "Canonical resource path", "schema": map[string]any{"type": "string"}}
	}
	return map[string]any{
		"description": "Resource",
		"headers":     headers,
		"content":     jsonContent(schemaRef(schema)),
	}
}

func errorResponse(description string) map[string]any {
	return map[string]any{"description": description, "content": jsonContent(schemaRef("Error"))}
}

func nameParameter() map[string]any {
	return map[string]any{
		"name": "name", "in": "path", "required": true,
		"schema": map[string]any{
			"type": "string", "maxLength": 253,
			"pattern": `^[a-z0-9](?:[-a-z0-9.]{0,251}[a-z0-9])?$`,
		},
	}
}

func ifMatchParameter() map[string]any {
	return map[string]any{
		"name": "If-Match", "in": "header", "required": true,
		"description": "ETag or resourceVersion returned by the latest read",
		"schema":      map[string]any{"type": "string"},
	}
}

func etagHeader() map[string]any {
	return map[string]any{"description": "Quoted storage modification revision", "schema": map[string]any{"type": "string"}}
}

func resourceVersionHeader() map[string]any {
	return map[string]any{"description": "Storage revision used for the list", "schema": map[string]any{"type": "string"}}
}

func schemaRef(name string) map[string]any {
	return map[string]any{"$ref": "#/components/schemas/" + name}
}

func jsonContent(schema map[string]any) map[string]any {
	return map[string]any{"application/json": map[string]any{"schema": schema}}
}

func operationSet(operations []string) map[string]bool {
	result := make(map[string]bool, len(operations))
	for _, operation := range operations {
		result[operation] = true
	}
	return result
}

func rewriteLocalRefs(value any) any {
	switch typed := value.(type) {
	case map[string]any:
		for key, child := range typed {
			if key == "$ref" {
				if ref, ok := child.(string); ok && strings.HasPrefix(ref, "#/") && !strings.HasPrefix(ref, "#/components/") {
					typed[key] = "#/components/schemas/" + strings.TrimPrefix(ref, "#/")
				}
				continue
			}
			typed[key] = rewriteLocalRefs(child)
		}
	case []any:
		for index := range typed {
			typed[index] = rewriteLocalRefs(typed[index])
		}
	}
	return value
}

func writeRegistry(path, modelsImport, resourceImport string, modules []resourceModule) {
	var source strings.Builder
	source.WriteString("// Code generated by generate-api; DO NOT EDIT.\n")
	source.WriteString("// registry.gen.go registers every discovered resource spec type with the generic API runtime.\n\n")
	source.WriteString("package registry\n\n")
	source.WriteString("import (\n")
	fmt.Fprintf(&source, "\tapigen %q\n", modelsImport)
	fmt.Fprintf(&source, "\t%q\n", resourceImport)
	source.WriteString(")\n\n")
	for _, module := range modules {
		metadata := module.Metadata
		fmt.Fprintf(
			&source,
			"// %s is the concrete controller-facing resource for %s.\n"+
				"type %s struct {\n"+
				"\tAPIVersion string `json:\"apiVersion\"`\n"+
				"\tKind string `json:\"kind\"`\n"+
				"\tMetadata resource.Metadata `json:\"metadata\"`\n"+
				"\tSpec apigen.%s `json:\"spec\"`\n"+
				"\tStatus map[string]any `json:\"status,omitempty\"`\n"+
				"}\n\n"+
				"// New%s constructs a %s with its generated type identity.\n"+
				"func New%s(metadata resource.Metadata, spec apigen.%s) %s {\n"+
				"\treturn %s{\n"+
				"\t\tAPIVersion: %sResource.APIVersion,\n"+
				"\t\tKind: %sResource.Kind,\n"+
				"\t\tMetadata: metadata,\n"+
				"\t\tSpec: spec,\n"+
				"\t}\n"+
				"}\n\n"+
				"// Encode converts the typed %s into the generic storage representation.\n"+
				"func (value %s) Encode() (resource.Resource, error) {\n"+
				"\treturn encodeResource(%sResource.Definition, value.APIVersion, value.Kind, value.Metadata, value.Spec, value.Status)\n"+
				"}\n\n"+
				"// %sDefinition adds concrete %s decoding to the shared API definition.\n"+
				"type %sDefinition struct {\n"+
				"\tDefinition\n"+
				"}\n\n"+
				"// Decode converts a generic storage resource into a typed %s.\n"+
				"func (definition %sDefinition) Decode(value resource.Resource) (%s, error) {\n"+
				"\tspec, err := decodeResourceSpec[apigen.%s](definition.Definition, value)\n"+
				"\tif err != nil {\n"+
				"\t\treturn %s{}, err\n"+
				"\t}\n"+
				"\treturn %s{\n"+
				"\t\tAPIVersion: value.APIVersion,\n"+
				"\t\tKind: value.Kind,\n"+
				"\t\tMetadata: value.Metadata,\n"+
				"\t\tSpec: spec,\n"+
				"\t\tStatus: value.Status,\n"+
				"\t}, nil\n"+
				"}\n\n",
			metadata.Kind,
			metadata.Kind,
			metadata.Kind,
			metadata.SpecSchema,
			metadata.Kind,
			metadata.Kind,
			metadata.Kind,
			metadata.SpecSchema,
			metadata.Kind,
			metadata.Kind,
			metadata.Kind,
			metadata.Kind,
			metadata.Kind,
			metadata.Kind,
			metadata.Kind,
			metadata.Kind,
			metadata.Kind,
			metadata.Kind,
			metadata.Kind,
			metadata.Kind,
			metadata.Kind,
			metadata.SpecSchema,
			metadata.Kind,
			metadata.Kind,
		)
	}
	for _, module := range modules {
		metadata := module.Metadata
		fmt.Fprintf(
			&source,
			"var %sResource = %sDefinition{Definition: NewDefinition[apigen.%s](%q, %q, %q, %q)}\n",
			metadata.Kind,
			metadata.Kind,
			metadata.SpecSchema,
			metadata.APIVersion,
			metadata.PathPrefix,
			metadata.Kind,
			metadata.Plural,
		)
	}
	source.WriteString("\n")
	source.WriteString("var Definitions = []Definition{\n")
	for _, module := range modules {
		metadata := module.Metadata
		fmt.Fprintf(&source, "\t%sResource.Definition,\n", metadata.Kind)
	}
	source.WriteString("}\n")
	formatted, err := format.Source([]byte(source.String()))
	if err != nil {
		fail("format generated resource registry: %v", err)
	}
	writeFile(path, formatted)
}

func readYAMLMap(path string) map[string]any {
	data, err := os.ReadFile(path)
	if err != nil {
		fail("read %s: %v", path, err)
	}
	var result map[string]any
	if err := yaml.Unmarshal(data, &result); err != nil {
		fail("decode %s: %v", path, err)
	}
	return result
}

func requiredMap(parent map[string]any, key string) map[string]any {
	value, ok := parent[key].(map[string]any)
	if !ok {
		fail("OpenAPI base field %q must be an object", key)
	}
	return value
}

func writeFile(path string, data []byte) {
	if err := os.WriteFile(path, data, 0o644); err != nil {
		fail("write %s: %v", path, err)
	}
}

func fail(format string, values ...any) {
	_, _ = fmt.Fprintf(os.Stderr, format+"\n", values...)
	os.Exit(1)
}
