// Code generated by generate-api; DO NOT EDIT.
// registry.gen.go registers every discovered resource spec type with the generic API runtime.

package registry

import (
	apigen "github.com/asdf57/prov-controller-test/go/internal/api/gen"
	"github.com/asdf57/prov-controller-test/go/internal/resource"
)

// GitRepository is the concrete controller-facing resource for GitRepository.
type GitRepository struct {
	APIVersion string                   `json:"apiVersion"`
	Kind       string                   `json:"kind"`
	Metadata   resource.Metadata        `json:"metadata"`
	Spec       apigen.GitRepositorySpec `json:"spec"`
	Status     map[string]any           `json:"status,omitempty"`
}

// NewGitRepository constructs a GitRepository with its generated type identity.
func NewGitRepository(metadata resource.Metadata, spec apigen.GitRepositorySpec) GitRepository {
	return GitRepository{
		APIVersion: GitRepositoryResource.APIVersion,
		Kind:       GitRepositoryResource.Kind,
		Metadata:   metadata,
		Spec:       spec,
	}
}

// Encode converts the typed GitRepository into the generic storage representation.
func (value GitRepository) Encode() (resource.Resource, error) {
	return encodeResource(GitRepositoryResource.Definition, value.APIVersion, value.Kind, value.Metadata, value.Spec, value.Status)
}

// GitRepositoryDefinition adds concrete GitRepository decoding to the shared API definition.
type GitRepositoryDefinition struct {
	Definition
}

// Decode converts a generic storage resource into a typed GitRepository.
func (definition GitRepositoryDefinition) Decode(value resource.Resource) (GitRepository, error) {
	spec, err := decodeResourceSpec[apigen.GitRepositorySpec](definition.Definition, value)
	if err != nil {
		return GitRepository{}, err
	}
	return GitRepository{
		APIVersion: value.APIVersion,
		Kind:       value.Kind,
		Metadata:   value.Metadata,
		Spec:       spec,
		Status:     value.Status,
	}, nil
}

// InventoryCaptureGroup is the concrete controller-facing resource for InventoryCaptureGroup.
type InventoryCaptureGroup struct {
	APIVersion string                           `json:"apiVersion"`
	Kind       string                           `json:"kind"`
	Metadata   resource.Metadata                `json:"metadata"`
	Spec       apigen.InventoryCaptureGroupSpec `json:"spec"`
	Status     map[string]any                   `json:"status,omitempty"`
}

// NewInventoryCaptureGroup constructs a InventoryCaptureGroup with its generated type identity.
func NewInventoryCaptureGroup(metadata resource.Metadata, spec apigen.InventoryCaptureGroupSpec) InventoryCaptureGroup {
	return InventoryCaptureGroup{
		APIVersion: InventoryCaptureGroupResource.APIVersion,
		Kind:       InventoryCaptureGroupResource.Kind,
		Metadata:   metadata,
		Spec:       spec,
	}
}

// Encode converts the typed InventoryCaptureGroup into the generic storage representation.
func (value InventoryCaptureGroup) Encode() (resource.Resource, error) {
	return encodeResource(InventoryCaptureGroupResource.Definition, value.APIVersion, value.Kind, value.Metadata, value.Spec, value.Status)
}

// InventoryCaptureGroupDefinition adds concrete InventoryCaptureGroup decoding to the shared API definition.
type InventoryCaptureGroupDefinition struct {
	Definition
}

// Decode converts a generic storage resource into a typed InventoryCaptureGroup.
func (definition InventoryCaptureGroupDefinition) Decode(value resource.Resource) (InventoryCaptureGroup, error) {
	spec, err := decodeResourceSpec[apigen.InventoryCaptureGroupSpec](definition.Definition, value)
	if err != nil {
		return InventoryCaptureGroup{}, err
	}
	return InventoryCaptureGroup{
		APIVersion: value.APIVersion,
		Kind:       value.Kind,
		Metadata:   value.Metadata,
		Spec:       spec,
		Status:     value.Status,
	}, nil
}

// InventoryPublication is the concrete controller-facing resource for InventoryPublication.
type InventoryPublication struct {
	APIVersion string                          `json:"apiVersion"`
	Kind       string                          `json:"kind"`
	Metadata   resource.Metadata               `json:"metadata"`
	Spec       apigen.InventoryPublicationSpec `json:"spec"`
	Status     map[string]any                  `json:"status,omitempty"`
}

// NewInventoryPublication constructs a InventoryPublication with its generated type identity.
func NewInventoryPublication(metadata resource.Metadata, spec apigen.InventoryPublicationSpec) InventoryPublication {
	return InventoryPublication{
		APIVersion: InventoryPublicationResource.APIVersion,
		Kind:       InventoryPublicationResource.Kind,
		Metadata:   metadata,
		Spec:       spec,
	}
}

// Encode converts the typed InventoryPublication into the generic storage representation.
func (value InventoryPublication) Encode() (resource.Resource, error) {
	return encodeResource(InventoryPublicationResource.Definition, value.APIVersion, value.Kind, value.Metadata, value.Spec, value.Status)
}

// InventoryPublicationDefinition adds concrete InventoryPublication decoding to the shared API definition.
type InventoryPublicationDefinition struct {
	Definition
}

// Decode converts a generic storage resource into a typed InventoryPublication.
func (definition InventoryPublicationDefinition) Decode(value resource.Resource) (InventoryPublication, error) {
	spec, err := decodeResourceSpec[apigen.InventoryPublicationSpec](definition.Definition, value)
	if err != nil {
		return InventoryPublication{}, err
	}
	return InventoryPublication{
		APIVersion: value.APIVersion,
		Kind:       value.Kind,
		Metadata:   value.Metadata,
		Spec:       spec,
		Status:     value.Status,
	}, nil
}

// MachineReport is the concrete controller-facing resource for MachineReport.
type MachineReport struct {
	APIVersion string                   `json:"apiVersion"`
	Kind       string                   `json:"kind"`
	Metadata   resource.Metadata        `json:"metadata"`
	Spec       apigen.MachineReportSpec `json:"spec"`
	Status     map[string]any           `json:"status,omitempty"`
}

// NewMachineReport constructs a MachineReport with its generated type identity.
func NewMachineReport(metadata resource.Metadata, spec apigen.MachineReportSpec) MachineReport {
	return MachineReport{
		APIVersion: MachineReportResource.APIVersion,
		Kind:       MachineReportResource.Kind,
		Metadata:   metadata,
		Spec:       spec,
	}
}

// Encode converts the typed MachineReport into the generic storage representation.
func (value MachineReport) Encode() (resource.Resource, error) {
	return encodeResource(MachineReportResource.Definition, value.APIVersion, value.Kind, value.Metadata, value.Spec, value.Status)
}

// MachineReportDefinition adds concrete MachineReport decoding to the shared API definition.
type MachineReportDefinition struct {
	Definition
}

// Decode converts a generic storage resource into a typed MachineReport.
func (definition MachineReportDefinition) Decode(value resource.Resource) (MachineReport, error) {
	spec, err := decodeResourceSpec[apigen.MachineReportSpec](definition.Definition, value)
	if err != nil {
		return MachineReport{}, err
	}
	return MachineReport{
		APIVersion: value.APIVersion,
		Kind:       value.Kind,
		Metadata:   value.Metadata,
		Spec:       spec,
		Status:     value.Status,
	}, nil
}

// Machine is the concrete controller-facing resource for Machine.
type Machine struct {
	APIVersion string             `json:"apiVersion"`
	Kind       string             `json:"kind"`
	Metadata   resource.Metadata  `json:"metadata"`
	Spec       apigen.MachineSpec `json:"spec"`
	Status     map[string]any     `json:"status,omitempty"`
}

// NewMachine constructs a Machine with its generated type identity.
func NewMachine(metadata resource.Metadata, spec apigen.MachineSpec) Machine {
	return Machine{
		APIVersion: MachineResource.APIVersion,
		Kind:       MachineResource.Kind,
		Metadata:   metadata,
		Spec:       spec,
	}
}

// Encode converts the typed Machine into the generic storage representation.
func (value Machine) Encode() (resource.Resource, error) {
	return encodeResource(MachineResource.Definition, value.APIVersion, value.Kind, value.Metadata, value.Spec, value.Status)
}

// MachineDefinition adds concrete Machine decoding to the shared API definition.
type MachineDefinition struct {
	Definition
}

// Decode converts a generic storage resource into a typed Machine.
func (definition MachineDefinition) Decode(value resource.Resource) (Machine, error) {
	spec, err := decodeResourceSpec[apigen.MachineSpec](definition.Definition, value)
	if err != nil {
		return Machine{}, err
	}
	return Machine{
		APIVersion: value.APIVersion,
		Kind:       value.Kind,
		Metadata:   value.Metadata,
		Spec:       spec,
		Status:     value.Status,
	}, nil
}

// SecretStore is the concrete controller-facing resource for SecretStore.
type SecretStore struct {
	APIVersion string                 `json:"apiVersion"`
	Kind       string                 `json:"kind"`
	Metadata   resource.Metadata      `json:"metadata"`
	Spec       apigen.SecretStoreSpec `json:"spec"`
	Status     map[string]any         `json:"status,omitempty"`
}

// NewSecretStore constructs a SecretStore with its generated type identity.
func NewSecretStore(metadata resource.Metadata, spec apigen.SecretStoreSpec) SecretStore {
	return SecretStore{
		APIVersion: SecretStoreResource.APIVersion,
		Kind:       SecretStoreResource.Kind,
		Metadata:   metadata,
		Spec:       spec,
	}
}

// Encode converts the typed SecretStore into the generic storage representation.
func (value SecretStore) Encode() (resource.Resource, error) {
	return encodeResource(SecretStoreResource.Definition, value.APIVersion, value.Kind, value.Metadata, value.Spec, value.Status)
}

// SecretStoreDefinition adds concrete SecretStore decoding to the shared API definition.
type SecretStoreDefinition struct {
	Definition
}

// Decode converts a generic storage resource into a typed SecretStore.
func (definition SecretStoreDefinition) Decode(value resource.Resource) (SecretStore, error) {
	spec, err := decodeResourceSpec[apigen.SecretStoreSpec](definition.Definition, value)
	if err != nil {
		return SecretStore{}, err
	}
	return SecretStore{
		APIVersion: value.APIVersion,
		Kind:       value.Kind,
		Metadata:   value.Metadata,
		Spec:       spec,
		Status:     value.Status,
	}, nil
}

// Secret is the concrete controller-facing resource for Secret.
type Secret struct {
	APIVersion string            `json:"apiVersion"`
	Kind       string            `json:"kind"`
	Metadata   resource.Metadata `json:"metadata"`
	Spec       apigen.SecretSpec `json:"spec"`
	Status     map[string]any    `json:"status,omitempty"`
}

// NewSecret constructs a Secret with its generated type identity.
func NewSecret(metadata resource.Metadata, spec apigen.SecretSpec) Secret {
	return Secret{
		APIVersion: SecretResource.APIVersion,
		Kind:       SecretResource.Kind,
		Metadata:   metadata,
		Spec:       spec,
	}
}

// Encode converts the typed Secret into the generic storage representation.
func (value Secret) Encode() (resource.Resource, error) {
	return encodeResource(SecretResource.Definition, value.APIVersion, value.Kind, value.Metadata, value.Spec, value.Status)
}

// SecretDefinition adds concrete Secret decoding to the shared API definition.
type SecretDefinition struct {
	Definition
}

// Decode converts a generic storage resource into a typed Secret.
func (definition SecretDefinition) Decode(value resource.Resource) (Secret, error) {
	spec, err := decodeResourceSpec[apigen.SecretSpec](definition.Definition, value)
	if err != nil {
		return Secret{}, err
	}
	return Secret{
		APIVersion: value.APIVersion,
		Kind:       value.Kind,
		Metadata:   value.Metadata,
		Spec:       spec,
		Status:     value.Status,
	}, nil
}

// Server is the concrete controller-facing resource for Server.
type Server struct {
	APIVersion string            `json:"apiVersion"`
	Kind       string            `json:"kind"`
	Metadata   resource.Metadata `json:"metadata"`
	Spec       apigen.ServerSpec `json:"spec"`
	Status     map[string]any    `json:"status,omitempty"`
}

// NewServer constructs a Server with its generated type identity.
func NewServer(metadata resource.Metadata, spec apigen.ServerSpec) Server {
	return Server{
		APIVersion: ServerResource.APIVersion,
		Kind:       ServerResource.Kind,
		Metadata:   metadata,
		Spec:       spec,
	}
}

// Encode converts the typed Server into the generic storage representation.
func (value Server) Encode() (resource.Resource, error) {
	return encodeResource(ServerResource.Definition, value.APIVersion, value.Kind, value.Metadata, value.Spec, value.Status)
}

// ServerDefinition adds concrete Server decoding to the shared API definition.
type ServerDefinition struct {
	Definition
}

// Decode converts a generic storage resource into a typed Server.
func (definition ServerDefinition) Decode(value resource.Resource) (Server, error) {
	spec, err := decodeResourceSpec[apigen.ServerSpec](definition.Definition, value)
	if err != nil {
		return Server{}, err
	}
	return Server{
		APIVersion: value.APIVersion,
		Kind:       value.Kind,
		Metadata:   value.Metadata,
		Spec:       spec,
		Status:     value.Status,
	}, nil
}

// SSHKeyPair is the concrete controller-facing resource for SSHKeyPair.
type SSHKeyPair struct {
	APIVersion string                `json:"apiVersion"`
	Kind       string                `json:"kind"`
	Metadata   resource.Metadata     `json:"metadata"`
	Spec       apigen.SSHKeyPairSpec `json:"spec"`
	Status     map[string]any        `json:"status,omitempty"`
}

// NewSSHKeyPair constructs a SSHKeyPair with its generated type identity.
func NewSSHKeyPair(metadata resource.Metadata, spec apigen.SSHKeyPairSpec) SSHKeyPair {
	return SSHKeyPair{
		APIVersion: SSHKeyPairResource.APIVersion,
		Kind:       SSHKeyPairResource.Kind,
		Metadata:   metadata,
		Spec:       spec,
	}
}

// Encode converts the typed SSHKeyPair into the generic storage representation.
func (value SSHKeyPair) Encode() (resource.Resource, error) {
	return encodeResource(SSHKeyPairResource.Definition, value.APIVersion, value.Kind, value.Metadata, value.Spec, value.Status)
}

// SSHKeyPairDefinition adds concrete SSHKeyPair decoding to the shared API definition.
type SSHKeyPairDefinition struct {
	Definition
}

// Decode converts a generic storage resource into a typed SSHKeyPair.
func (definition SSHKeyPairDefinition) Decode(value resource.Resource) (SSHKeyPair, error) {
	spec, err := decodeResourceSpec[apigen.SSHKeyPairSpec](definition.Definition, value)
	if err != nil {
		return SSHKeyPair{}, err
	}
	return SSHKeyPair{
		APIVersion: value.APIVersion,
		Kind:       value.Kind,
		Metadata:   value.Metadata,
		Spec:       spec,
		Status:     value.Status,
	}, nil
}

var GitRepositoryResource = GitRepositoryDefinition{Definition: NewDefinition[apigen.GitRepositorySpec]("homelab.io/v1alpha1", "/api/v1alpha1", "GitRepository", "git-repositories", "", []string(nil))}
var InventoryCaptureGroupResource = InventoryCaptureGroupDefinition{Definition: NewDefinition[apigen.InventoryCaptureGroupSpec]("homelab.io/v1alpha1", "/api/v1alpha1", "InventoryCaptureGroup", "inventory-capture-groups", "InventoryCaptureGroupStatus", []string(nil))}
var InventoryPublicationResource = InventoryPublicationDefinition{Definition: NewDefinition[apigen.InventoryPublicationSpec]("homelab.io/v1alpha1", "/api/v1alpha1", "InventoryPublication", "inventory-publications", "InventoryPublicationStatus", []string(nil))}
var MachineReportResource = MachineReportDefinition{Definition: NewDefinition[apigen.MachineReportSpec]("homelab.io/v1alpha1", "/api/v1alpha1", "MachineReport", "machine-reports", "", []string(nil))}
var MachineResource = MachineDefinition{Definition: NewDefinition[apigen.MachineSpec]("homelab.io/v1alpha1", "/api/v1alpha1", "Machine", "machines", "MachineStatus", []string(nil))}
var SecretStoreResource = SecretStoreDefinition{Definition: NewDefinition[apigen.SecretStoreSpec]("homelab.io/v1alpha1", "/api/v1alpha1", "SecretStore", "secret-stores", "", []string(nil))}
var SecretResource = SecretDefinition{Definition: NewDefinition[apigen.SecretSpec]("homelab.io/v1alpha1", "/api/v1alpha1", "Secret", "secrets", "SecretStatus", []string{"homelab.io/secret-cleanup"})}
var ServerResource = ServerDefinition{Definition: NewDefinition[apigen.ServerSpec]("homelab.io/v1alpha1", "/api/v1alpha1", "Server", "servers", "ServerStatus", []string(nil))}
var SSHKeyPairResource = SSHKeyPairDefinition{Definition: NewDefinition[apigen.SSHKeyPairSpec]("homelab.io/v1alpha1", "/api/v1alpha1", "SSHKeyPair", "ssh-key-pairs", "SSHKeyPairStatus", []string{"homelab.io/ssh-key-pair-cleanup"})}

var Definitions = []Definition{
	GitRepositoryResource.Definition,
	InventoryCaptureGroupResource.Definition,
	InventoryPublicationResource.Definition,
	MachineReportResource.Definition,
	MachineResource.Definition,
	SecretStoreResource.Definition,
	SecretResource.Definition,
	ServerResource.Definition,
	SSHKeyPairResource.Definition,
}
