// Code generated by generate-api; DO NOT EDIT.
// registry.gen.go registers every discovered resource spec type with the generic API runtime.

package registry

import (
	apigen "github.com/asdf57/stigmergy/internal/api/gen"
	"github.com/asdf57/stigmergy/internal/resource"
)

// CommandsPipeline is the concrete controller-facing resource for CommandsPipeline.
type CommandsPipeline struct {
	APIVersion string                         `json:"apiVersion"`
	Kind       string                         `json:"kind"`
	Metadata   resource.Metadata              `json:"metadata"`
	Spec       apigen.CommandsPipelineSpec    `json:"spec"`
	Status     *apigen.CommandsPipelineStatus `json:"status,omitempty"`
}

// NewCommandsPipeline constructs a CommandsPipeline with its generated type identity.
func NewCommandsPipeline(metadata resource.Metadata, spec apigen.CommandsPipelineSpec) CommandsPipeline {
	return CommandsPipeline{
		APIVersion: CommandsPipelineResource.APIVersion,
		Kind:       CommandsPipelineResource.Kind,
		Metadata:   metadata,
		Spec:       spec,
	}
}

// Encode converts the typed CommandsPipeline into the generic storage representation.
func (value CommandsPipeline) Encode() (resource.Resource, error) {
	return encodeResource(CommandsPipelineResource.Definition, value.APIVersion, value.Kind, value.Metadata, value.Spec, value.Status)
}

// CommandsPipelineDefinition adds concrete CommandsPipeline decoding to the shared API definition.
type CommandsPipelineDefinition struct {
	Definition
}

// EncodeStatus converts a typed CommandsPipeline status to the generic storage representation.
func (definition CommandsPipelineDefinition) EncodeStatus(status *apigen.CommandsPipelineStatus) (map[string]any, error) {
	return encodeStatus(definition.Kind, status)
}

// Decode converts a generic storage resource into a typed CommandsPipeline.
func (definition CommandsPipelineDefinition) Decode(value resource.Resource) (CommandsPipeline, error) {
	spec, err := decodeResourceSpec[apigen.CommandsPipelineSpec](definition.Definition, value)
	if err != nil {
		return CommandsPipeline{}, err
	}
	status, err := decodeStoredStatus[apigen.CommandsPipelineStatus](definition.Kind, value.Status)
	if err != nil {
		return CommandsPipeline{}, err
	}
	return CommandsPipeline{
		APIVersion: value.APIVersion,
		Kind:       value.Kind,
		Metadata:   value.Metadata,
		Spec:       spec,
		Status:     status,
	}, nil
}

// DNSRecord is the concrete controller-facing resource for DNSRecord.
type DNSRecord struct {
	APIVersion string                  `json:"apiVersion"`
	Kind       string                  `json:"kind"`
	Metadata   resource.Metadata       `json:"metadata"`
	Spec       apigen.DNSRecordSpec    `json:"spec"`
	Status     *apigen.DNSRecordStatus `json:"status,omitempty"`
}

// NewDNSRecord constructs a DNSRecord with its generated type identity.
func NewDNSRecord(metadata resource.Metadata, spec apigen.DNSRecordSpec) DNSRecord {
	return DNSRecord{
		APIVersion: DNSRecordResource.APIVersion,
		Kind:       DNSRecordResource.Kind,
		Metadata:   metadata,
		Spec:       spec,
	}
}

// Encode converts the typed DNSRecord into the generic storage representation.
func (value DNSRecord) Encode() (resource.Resource, error) {
	return encodeResource(DNSRecordResource.Definition, value.APIVersion, value.Kind, value.Metadata, value.Spec, value.Status)
}

// DNSRecordDefinition adds concrete DNSRecord decoding to the shared API definition.
type DNSRecordDefinition struct {
	Definition
}

// EncodeStatus converts a typed DNSRecord status to the generic storage representation.
func (definition DNSRecordDefinition) EncodeStatus(status *apigen.DNSRecordStatus) (map[string]any, error) {
	return encodeStatus(definition.Kind, status)
}

// Decode converts a generic storage resource into a typed DNSRecord.
func (definition DNSRecordDefinition) Decode(value resource.Resource) (DNSRecord, error) {
	spec, err := decodeResourceSpec[apigen.DNSRecordSpec](definition.Definition, value)
	if err != nil {
		return DNSRecord{}, err
	}
	status, err := decodeStoredStatus[apigen.DNSRecordStatus](definition.Kind, value.Status)
	if err != nil {
		return DNSRecord{}, err
	}
	return DNSRecord{
		APIVersion: value.APIVersion,
		Kind:       value.Kind,
		Metadata:   value.Metadata,
		Spec:       spec,
		Status:     status,
	}, nil
}

// GitRepository is the concrete controller-facing resource for GitRepository.
type GitRepository struct {
	APIVersion string                      `json:"apiVersion"`
	Kind       string                      `json:"kind"`
	Metadata   resource.Metadata           `json:"metadata"`
	Spec       apigen.GitRepositorySpec    `json:"spec"`
	Status     *apigen.GitRepositoryStatus `json:"status,omitempty"`
}

// NewGitRepository constructs a GitRepository with its generated type identity.
func NewGitRepository(metadata resource.Metadata, spec apigen.GitRepositorySpec) GitRepository {
	return GitRepository{
		APIVersion: GitRepositoryResource.APIVersion,
		Kind:       GitRepositoryResource.Kind,
		Metadata:   metadata,
		Spec:       spec,
	}
}

// Encode converts the typed GitRepository into the generic storage representation.
func (value GitRepository) Encode() (resource.Resource, error) {
	return encodeResource(GitRepositoryResource.Definition, value.APIVersion, value.Kind, value.Metadata, value.Spec, value.Status)
}

// GitRepositoryDefinition adds concrete GitRepository decoding to the shared API definition.
type GitRepositoryDefinition struct {
	Definition
}

// EncodeStatus converts a typed GitRepository status to the generic storage representation.
func (definition GitRepositoryDefinition) EncodeStatus(status *apigen.GitRepositoryStatus) (map[string]any, error) {
	return encodeStatus(definition.Kind, status)
}

// Decode converts a generic storage resource into a typed GitRepository.
func (definition GitRepositoryDefinition) Decode(value resource.Resource) (GitRepository, error) {
	spec, err := decodeResourceSpec[apigen.GitRepositorySpec](definition.Definition, value)
	if err != nil {
		return GitRepository{}, err
	}
	status, err := decodeStoredStatus[apigen.GitRepositoryStatus](definition.Kind, value.Status)
	if err != nil {
		return GitRepository{}, err
	}
	return GitRepository{
		APIVersion: value.APIVersion,
		Kind:       value.Kind,
		Metadata:   value.Metadata,
		Spec:       spec,
		Status:     status,
	}, nil
}

// InventoryCaptureGroup is the concrete controller-facing resource for InventoryCaptureGroup.
type InventoryCaptureGroup struct {
	APIVersion string                              `json:"apiVersion"`
	Kind       string                              `json:"kind"`
	Metadata   resource.Metadata                   `json:"metadata"`
	Spec       apigen.InventoryCaptureGroupSpec    `json:"spec"`
	Status     *apigen.InventoryCaptureGroupStatus `json:"status,omitempty"`
}

// NewInventoryCaptureGroup constructs a InventoryCaptureGroup with its generated type identity.
func NewInventoryCaptureGroup(metadata resource.Metadata, spec apigen.InventoryCaptureGroupSpec) InventoryCaptureGroup {
	return InventoryCaptureGroup{
		APIVersion: InventoryCaptureGroupResource.APIVersion,
		Kind:       InventoryCaptureGroupResource.Kind,
		Metadata:   metadata,
		Spec:       spec,
	}
}

// Encode converts the typed InventoryCaptureGroup into the generic storage representation.
func (value InventoryCaptureGroup) Encode() (resource.Resource, error) {
	return encodeResource(InventoryCaptureGroupResource.Definition, value.APIVersion, value.Kind, value.Metadata, value.Spec, value.Status)
}

// InventoryCaptureGroupDefinition adds concrete InventoryCaptureGroup decoding to the shared API definition.
type InventoryCaptureGroupDefinition struct {
	Definition
}

// EncodeStatus converts a typed InventoryCaptureGroup status to the generic storage representation.
func (definition InventoryCaptureGroupDefinition) EncodeStatus(status *apigen.InventoryCaptureGroupStatus) (map[string]any, error) {
	return encodeStatus(definition.Kind, status)
}

// Decode converts a generic storage resource into a typed InventoryCaptureGroup.
func (definition InventoryCaptureGroupDefinition) Decode(value resource.Resource) (InventoryCaptureGroup, error) {
	spec, err := decodeResourceSpec[apigen.InventoryCaptureGroupSpec](definition.Definition, value)
	if err != nil {
		return InventoryCaptureGroup{}, err
	}
	status, err := decodeStoredStatus[apigen.InventoryCaptureGroupStatus](definition.Kind, value.Status)
	if err != nil {
		return InventoryCaptureGroup{}, err
	}
	return InventoryCaptureGroup{
		APIVersion: value.APIVersion,
		Kind:       value.Kind,
		Metadata:   value.Metadata,
		Spec:       spec,
		Status:     status,
	}, nil
}

// InventoryPublication is the concrete controller-facing resource for InventoryPublication.
type InventoryPublication struct {
	APIVersion string                             `json:"apiVersion"`
	Kind       string                             `json:"kind"`
	Metadata   resource.Metadata                  `json:"metadata"`
	Spec       apigen.InventoryPublicationSpec    `json:"spec"`
	Status     *apigen.InventoryPublicationStatus `json:"status,omitempty"`
}

// NewInventoryPublication constructs a InventoryPublication with its generated type identity.
func NewInventoryPublication(metadata resource.Metadata, spec apigen.InventoryPublicationSpec) InventoryPublication {
	return InventoryPublication{
		APIVersion: InventoryPublicationResource.APIVersion,
		Kind:       InventoryPublicationResource.Kind,
		Metadata:   metadata,
		Spec:       spec,
	}
}

// Encode converts the typed InventoryPublication into the generic storage representation.
func (value InventoryPublication) Encode() (resource.Resource, error) {
	return encodeResource(InventoryPublicationResource.Definition, value.APIVersion, value.Kind, value.Metadata, value.Spec, value.Status)
}

// InventoryPublicationDefinition adds concrete InventoryPublication decoding to the shared API definition.
type InventoryPublicationDefinition struct {
	Definition
}

// EncodeStatus converts a typed InventoryPublication status to the generic storage representation.
func (definition InventoryPublicationDefinition) EncodeStatus(status *apigen.InventoryPublicationStatus) (map[string]any, error) {
	return encodeStatus(definition.Kind, status)
}

// Decode converts a generic storage resource into a typed InventoryPublication.
func (definition InventoryPublicationDefinition) Decode(value resource.Resource) (InventoryPublication, error) {
	spec, err := decodeResourceSpec[apigen.InventoryPublicationSpec](definition.Definition, value)
	if err != nil {
		return InventoryPublication{}, err
	}
	status, err := decodeStoredStatus[apigen.InventoryPublicationStatus](definition.Kind, value.Status)
	if err != nil {
		return InventoryPublication{}, err
	}
	return InventoryPublication{
		APIVersion: value.APIVersion,
		Kind:       value.Kind,
		Metadata:   value.Metadata,
		Spec:       spec,
		Status:     status,
	}, nil
}

// MachineReport is the concrete controller-facing resource for MachineReport.
type MachineReport struct {
	APIVersion string                   `json:"apiVersion"`
	Kind       string                   `json:"kind"`
	Metadata   resource.Metadata        `json:"metadata"`
	Spec       apigen.MachineReportSpec `json:"spec"`
}

// NewMachineReport constructs a MachineReport with its generated type identity.
func NewMachineReport(metadata resource.Metadata, spec apigen.MachineReportSpec) MachineReport {
	return MachineReport{
		APIVersion: MachineReportResource.APIVersion,
		Kind:       MachineReportResource.Kind,
		Metadata:   metadata,
		Spec:       spec,
	}
}

// Encode converts the typed MachineReport into the generic storage representation.
func (value MachineReport) Encode() (resource.Resource, error) {
	return encodeResource(MachineReportResource.Definition, value.APIVersion, value.Kind, value.Metadata, value.Spec, nil)
}

// MachineReportDefinition adds concrete MachineReport decoding to the shared API definition.
type MachineReportDefinition struct {
	Definition
}

// Decode converts a generic storage resource into a typed MachineReport.
func (definition MachineReportDefinition) Decode(value resource.Resource) (MachineReport, error) {
	spec, err := decodeResourceSpec[apigen.MachineReportSpec](definition.Definition, value)
	if err != nil {
		return MachineReport{}, err
	}
	return MachineReport{
		APIVersion: value.APIVersion,
		Kind:       value.Kind,
		Metadata:   value.Metadata,
		Spec:       spec,
	}, nil
}

// Machine is the concrete controller-facing resource for Machine.
type Machine struct {
	APIVersion string                `json:"apiVersion"`
	Kind       string                `json:"kind"`
	Metadata   resource.Metadata     `json:"metadata"`
	Spec       apigen.MachineSpec    `json:"spec"`
	Status     *apigen.MachineStatus `json:"status,omitempty"`
}

// NewMachine constructs a Machine with its generated type identity.
func NewMachine(metadata resource.Metadata, spec apigen.MachineSpec) Machine {
	return Machine{
		APIVersion: MachineResource.APIVersion,
		Kind:       MachineResource.Kind,
		Metadata:   metadata,
		Spec:       spec,
	}
}

// Encode converts the typed Machine into the generic storage representation.
func (value Machine) Encode() (resource.Resource, error) {
	return encodeResource(MachineResource.Definition, value.APIVersion, value.Kind, value.Metadata, value.Spec, value.Status)
}

// MachineDefinition adds concrete Machine decoding to the shared API definition.
type MachineDefinition struct {
	Definition
}

// EncodeStatus converts a typed Machine status to the generic storage representation.
func (definition MachineDefinition) EncodeStatus(status *apigen.MachineStatus) (map[string]any, error) {
	return encodeStatus(definition.Kind, status)
}

// Decode converts a generic storage resource into a typed Machine.
func (definition MachineDefinition) Decode(value resource.Resource) (Machine, error) {
	spec, err := decodeResourceSpec[apigen.MachineSpec](definition.Definition, value)
	if err != nil {
		return Machine{}, err
	}
	status, err := decodeStoredStatus[apigen.MachineStatus](definition.Kind, value.Status)
	if err != nil {
		return Machine{}, err
	}
	return Machine{
		APIVersion: value.APIVersion,
		Kind:       value.Kind,
		Metadata:   value.Metadata,
		Spec:       spec,
		Status:     status,
	}, nil
}

// PipelineProvider is the concrete controller-facing resource for PipelineProvider.
type PipelineProvider struct {
	APIVersion string                         `json:"apiVersion"`
	Kind       string                         `json:"kind"`
	Metadata   resource.Metadata              `json:"metadata"`
	Spec       apigen.PipelineProviderSpec    `json:"spec"`
	Status     *apigen.PipelineProviderStatus `json:"status,omitempty"`
}

// NewPipelineProvider constructs a PipelineProvider with its generated type identity.
func NewPipelineProvider(metadata resource.Metadata, spec apigen.PipelineProviderSpec) PipelineProvider {
	return PipelineProvider{
		APIVersion: PipelineProviderResource.APIVersion,
		Kind:       PipelineProviderResource.Kind,
		Metadata:   metadata,
		Spec:       spec,
	}
}

// Encode converts the typed PipelineProvider into the generic storage representation.
func (value PipelineProvider) Encode() (resource.Resource, error) {
	return encodeResource(PipelineProviderResource.Definition, value.APIVersion, value.Kind, value.Metadata, value.Spec, value.Status)
}

// PipelineProviderDefinition adds concrete PipelineProvider decoding to the shared API definition.
type PipelineProviderDefinition struct {
	Definition
}

// EncodeStatus converts a typed PipelineProvider status to the generic storage representation.
func (definition PipelineProviderDefinition) EncodeStatus(status *apigen.PipelineProviderStatus) (map[string]any, error) {
	return encodeStatus(definition.Kind, status)
}

// Decode converts a generic storage resource into a typed PipelineProvider.
func (definition PipelineProviderDefinition) Decode(value resource.Resource) (PipelineProvider, error) {
	spec, err := decodeResourceSpec[apigen.PipelineProviderSpec](definition.Definition, value)
	if err != nil {
		return PipelineProvider{}, err
	}
	status, err := decodeStoredStatus[apigen.PipelineProviderStatus](definition.Kind, value.Status)
	if err != nil {
		return PipelineProvider{}, err
	}
	return PipelineProvider{
		APIVersion: value.APIVersion,
		Kind:       value.Kind,
		Metadata:   value.Metadata,
		Spec:       spec,
		Status:     status,
	}, nil
}

// Pipeline is the concrete controller-facing resource for Pipeline.
type Pipeline struct {
	APIVersion string                 `json:"apiVersion"`
	Kind       string                 `json:"kind"`
	Metadata   resource.Metadata      `json:"metadata"`
	Spec       apigen.PipelineSpec    `json:"spec"`
	Status     *apigen.PipelineStatus `json:"status,omitempty"`
}

// NewPipeline constructs a Pipeline with its generated type identity.
func NewPipeline(metadata resource.Metadata, spec apigen.PipelineSpec) Pipeline {
	return Pipeline{
		APIVersion: PipelineResource.APIVersion,
		Kind:       PipelineResource.Kind,
		Metadata:   metadata,
		Spec:       spec,
	}
}

// Encode converts the typed Pipeline into the generic storage representation.
func (value Pipeline) Encode() (resource.Resource, error) {
	return encodeResource(PipelineResource.Definition, value.APIVersion, value.Kind, value.Metadata, value.Spec, value.Status)
}

// PipelineDefinition adds concrete Pipeline decoding to the shared API definition.
type PipelineDefinition struct {
	Definition
}

// EncodeStatus converts a typed Pipeline status to the generic storage representation.
func (definition PipelineDefinition) EncodeStatus(status *apigen.PipelineStatus) (map[string]any, error) {
	return encodeStatus(definition.Kind, status)
}

// Decode converts a generic storage resource into a typed Pipeline.
func (definition PipelineDefinition) Decode(value resource.Resource) (Pipeline, error) {
	spec, err := decodeResourceSpec[apigen.PipelineSpec](definition.Definition, value)
	if err != nil {
		return Pipeline{}, err
	}
	status, err := decodeStoredStatus[apigen.PipelineStatus](definition.Kind, value.Status)
	if err != nil {
		return Pipeline{}, err
	}
	return Pipeline{
		APIVersion: value.APIVersion,
		Kind:       value.Kind,
		Metadata:   value.Metadata,
		Spec:       spec,
		Status:     status,
	}, nil
}

// Router is the concrete controller-facing resource for Router.
type Router struct {
	APIVersion string               `json:"apiVersion"`
	Kind       string               `json:"kind"`
	Metadata   resource.Metadata    `json:"metadata"`
	Spec       apigen.RouterSpec    `json:"spec"`
	Status     *apigen.RouterStatus `json:"status,omitempty"`
}

// NewRouter constructs a Router with its generated type identity.
func NewRouter(metadata resource.Metadata, spec apigen.RouterSpec) Router {
	return Router{
		APIVersion: RouterResource.APIVersion,
		Kind:       RouterResource.Kind,
		Metadata:   metadata,
		Spec:       spec,
	}
}

// Encode converts the typed Router into the generic storage representation.
func (value Router) Encode() (resource.Resource, error) {
	return encodeResource(RouterResource.Definition, value.APIVersion, value.Kind, value.Metadata, value.Spec, value.Status)
}

// RouterDefinition adds concrete Router decoding to the shared API definition.
type RouterDefinition struct {
	Definition
}

// EncodeStatus converts a typed Router status to the generic storage representation.
func (definition RouterDefinition) EncodeStatus(status *apigen.RouterStatus) (map[string]any, error) {
	return encodeStatus(definition.Kind, status)
}

// Decode converts a generic storage resource into a typed Router.
func (definition RouterDefinition) Decode(value resource.Resource) (Router, error) {
	spec, err := decodeResourceSpec[apigen.RouterSpec](definition.Definition, value)
	if err != nil {
		return Router{}, err
	}
	status, err := decodeStoredStatus[apigen.RouterStatus](definition.Kind, value.Status)
	if err != nil {
		return Router{}, err
	}
	return Router{
		APIVersion: value.APIVersion,
		Kind:       value.Kind,
		Metadata:   value.Metadata,
		Spec:       spec,
		Status:     status,
	}, nil
}

// SecretStore is the concrete controller-facing resource for SecretStore.
type SecretStore struct {
	APIVersion string                 `json:"apiVersion"`
	Kind       string                 `json:"kind"`
	Metadata   resource.Metadata      `json:"metadata"`
	Spec       apigen.SecretStoreSpec `json:"spec"`
}

// NewSecretStore constructs a SecretStore with its generated type identity.
func NewSecretStore(metadata resource.Metadata, spec apigen.SecretStoreSpec) SecretStore {
	return SecretStore{
		APIVersion: SecretStoreResource.APIVersion,
		Kind:       SecretStoreResource.Kind,
		Metadata:   metadata,
		Spec:       spec,
	}
}

// Encode converts the typed SecretStore into the generic storage representation.
func (value SecretStore) Encode() (resource.Resource, error) {
	return encodeResource(SecretStoreResource.Definition, value.APIVersion, value.Kind, value.Metadata, value.Spec, nil)
}

// SecretStoreDefinition adds concrete SecretStore decoding to the shared API definition.
type SecretStoreDefinition struct {
	Definition
}

// Decode converts a generic storage resource into a typed SecretStore.
func (definition SecretStoreDefinition) Decode(value resource.Resource) (SecretStore, error) {
	spec, err := decodeResourceSpec[apigen.SecretStoreSpec](definition.Definition, value)
	if err != nil {
		return SecretStore{}, err
	}
	return SecretStore{
		APIVersion: value.APIVersion,
		Kind:       value.Kind,
		Metadata:   value.Metadata,
		Spec:       spec,
	}, nil
}

// Secret is the concrete controller-facing resource for Secret.
type Secret struct {
	APIVersion string               `json:"apiVersion"`
	Kind       string               `json:"kind"`
	Metadata   resource.Metadata    `json:"metadata"`
	Spec       apigen.SecretSpec    `json:"spec"`
	Status     *apigen.SecretStatus `json:"status,omitempty"`
}

// NewSecret constructs a Secret with its generated type identity.
func NewSecret(metadata resource.Metadata, spec apigen.SecretSpec) Secret {
	return Secret{
		APIVersion: SecretResource.APIVersion,
		Kind:       SecretResource.Kind,
		Metadata:   metadata,
		Spec:       spec,
	}
}

// Encode converts the typed Secret into the generic storage representation.
func (value Secret) Encode() (resource.Resource, error) {
	return encodeResource(SecretResource.Definition, value.APIVersion, value.Kind, value.Metadata, value.Spec, value.Status)
}

// SecretDefinition adds concrete Secret decoding to the shared API definition.
type SecretDefinition struct {
	Definition
}

// EncodeStatus converts a typed Secret status to the generic storage representation.
func (definition SecretDefinition) EncodeStatus(status *apigen.SecretStatus) (map[string]any, error) {
	return encodeStatus(definition.Kind, status)
}

// Decode converts a generic storage resource into a typed Secret.
func (definition SecretDefinition) Decode(value resource.Resource) (Secret, error) {
	spec, err := decodeResourceSpec[apigen.SecretSpec](definition.Definition, value)
	if err != nil {
		return Secret{}, err
	}
	status, err := decodeStoredStatus[apigen.SecretStatus](definition.Kind, value.Status)
	if err != nil {
		return Secret{}, err
	}
	return Secret{
		APIVersion: value.APIVersion,
		Kind:       value.Kind,
		Metadata:   value.Metadata,
		Spec:       spec,
		Status:     status,
	}, nil
}

// Server is the concrete controller-facing resource for Server.
type Server struct {
	APIVersion string               `json:"apiVersion"`
	Kind       string               `json:"kind"`
	Metadata   resource.Metadata    `json:"metadata"`
	Spec       apigen.ServerSpec    `json:"spec"`
	Status     *apigen.ServerStatus `json:"status,omitempty"`
}

// NewServer constructs a Server with its generated type identity.
func NewServer(metadata resource.Metadata, spec apigen.ServerSpec) Server {
	return Server{
		APIVersion: ServerResource.APIVersion,
		Kind:       ServerResource.Kind,
		Metadata:   metadata,
		Spec:       spec,
	}
}

// Encode converts the typed Server into the generic storage representation.
func (value Server) Encode() (resource.Resource, error) {
	return encodeResource(ServerResource.Definition, value.APIVersion, value.Kind, value.Metadata, value.Spec, value.Status)
}

// ServerDefinition adds concrete Server decoding to the shared API definition.
type ServerDefinition struct {
	Definition
}

// EncodeStatus converts a typed Server status to the generic storage representation.
func (definition ServerDefinition) EncodeStatus(status *apigen.ServerStatus) (map[string]any, error) {
	return encodeStatus(definition.Kind, status)
}

// Decode converts a generic storage resource into a typed Server.
func (definition ServerDefinition) Decode(value resource.Resource) (Server, error) {
	spec, err := decodeResourceSpec[apigen.ServerSpec](definition.Definition, value)
	if err != nil {
		return Server{}, err
	}
	status, err := decodeStoredStatus[apigen.ServerStatus](definition.Kind, value.Status)
	if err != nil {
		return Server{}, err
	}
	return Server{
		APIVersion: value.APIVersion,
		Kind:       value.Kind,
		Metadata:   value.Metadata,
		Spec:       spec,
		Status:     status,
	}, nil
}

// SSHKeyPair is the concrete controller-facing resource for SSHKeyPair.
type SSHKeyPair struct {
	APIVersion string                   `json:"apiVersion"`
	Kind       string                   `json:"kind"`
	Metadata   resource.Metadata        `json:"metadata"`
	Spec       apigen.SSHKeyPairSpec    `json:"spec"`
	Status     *apigen.SSHKeyPairStatus `json:"status,omitempty"`
}

// NewSSHKeyPair constructs a SSHKeyPair with its generated type identity.
func NewSSHKeyPair(metadata resource.Metadata, spec apigen.SSHKeyPairSpec) SSHKeyPair {
	return SSHKeyPair{
		APIVersion: SSHKeyPairResource.APIVersion,
		Kind:       SSHKeyPairResource.Kind,
		Metadata:   metadata,
		Spec:       spec,
	}
}

// Encode converts the typed SSHKeyPair into the generic storage representation.
func (value SSHKeyPair) Encode() (resource.Resource, error) {
	return encodeResource(SSHKeyPairResource.Definition, value.APIVersion, value.Kind, value.Metadata, value.Spec, value.Status)
}

// SSHKeyPairDefinition adds concrete SSHKeyPair decoding to the shared API definition.
type SSHKeyPairDefinition struct {
	Definition
}

// EncodeStatus converts a typed SSHKeyPair status to the generic storage representation.
func (definition SSHKeyPairDefinition) EncodeStatus(status *apigen.SSHKeyPairStatus) (map[string]any, error) {
	return encodeStatus(definition.Kind, status)
}

// Decode converts a generic storage resource into a typed SSHKeyPair.
func (definition SSHKeyPairDefinition) Decode(value resource.Resource) (SSHKeyPair, error) {
	spec, err := decodeResourceSpec[apigen.SSHKeyPairSpec](definition.Definition, value)
	if err != nil {
		return SSHKeyPair{}, err
	}
	status, err := decodeStoredStatus[apigen.SSHKeyPairStatus](definition.Kind, value.Status)
	if err != nil {
		return SSHKeyPair{}, err
	}
	return SSHKeyPair{
		APIVersion: value.APIVersion,
		Kind:       value.Kind,
		Metadata:   value.Metadata,
		Spec:       spec,
		Status:     status,
	}, nil
}

// UsernamePasswordCredential is the concrete controller-facing resource for UsernamePasswordCredential.
type UsernamePasswordCredential struct {
	APIVersion string                                   `json:"apiVersion"`
	Kind       string                                   `json:"kind"`
	Metadata   resource.Metadata                        `json:"metadata"`
	Spec       apigen.UsernamePasswordCredentialSpec    `json:"spec"`
	Status     *apigen.UsernamePasswordCredentialStatus `json:"status,omitempty"`
}

// NewUsernamePasswordCredential constructs a UsernamePasswordCredential with its generated type identity.
func NewUsernamePasswordCredential(metadata resource.Metadata, spec apigen.UsernamePasswordCredentialSpec) UsernamePasswordCredential {
	return UsernamePasswordCredential{
		APIVersion: UsernamePasswordCredentialResource.APIVersion,
		Kind:       UsernamePasswordCredentialResource.Kind,
		Metadata:   metadata,
		Spec:       spec,
	}
}

// Encode converts the typed UsernamePasswordCredential into the generic storage representation.
func (value UsernamePasswordCredential) Encode() (resource.Resource, error) {
	return encodeResource(UsernamePasswordCredentialResource.Definition, value.APIVersion, value.Kind, value.Metadata, value.Spec, value.Status)
}

// UsernamePasswordCredentialDefinition adds concrete UsernamePasswordCredential decoding to the shared API definition.
type UsernamePasswordCredentialDefinition struct {
	Definition
}

// EncodeStatus converts a typed UsernamePasswordCredential status to the generic storage representation.
func (definition UsernamePasswordCredentialDefinition) EncodeStatus(status *apigen.UsernamePasswordCredentialStatus) (map[string]any, error) {
	return encodeStatus(definition.Kind, status)
}

// Decode converts a generic storage resource into a typed UsernamePasswordCredential.
func (definition UsernamePasswordCredentialDefinition) Decode(value resource.Resource) (UsernamePasswordCredential, error) {
	spec, err := decodeResourceSpec[apigen.UsernamePasswordCredentialSpec](definition.Definition, value)
	if err != nil {
		return UsernamePasswordCredential{}, err
	}
	status, err := decodeStoredStatus[apigen.UsernamePasswordCredentialStatus](definition.Kind, value.Status)
	if err != nil {
		return UsernamePasswordCredential{}, err
	}
	return UsernamePasswordCredential{
		APIVersion: value.APIVersion,
		Kind:       value.Kind,
		Metadata:   value.Metadata,
		Spec:       spec,
		Status:     status,
	}, nil
}

var CommandsPipelineResource = CommandsPipelineDefinition{Definition: NewDefinition[apigen.CommandsPipelineSpec]("homelab.io/v1alpha1", "/api/v1alpha1", "CommandsPipeline", "commands-pipelines", "CommandsPipelineStatus", []string{"homelab.io/commands-pipeline-cleanup"})}
var DNSRecordResource = DNSRecordDefinition{Definition: NewDefinition[apigen.DNSRecordSpec]("homelab.io/v1alpha1", "/api/v1alpha1", "DNSRecord", "dns-records", "DNSRecordStatus", []string{"homelab.io/dns-record-cleanup"})}
var GitRepositoryResource = GitRepositoryDefinition{Definition: NewDefinition[apigen.GitRepositorySpec]("homelab.io/v1alpha1", "/api/v1alpha1", "GitRepository", "git-repositories", "GitRepositoryStatus", []string(nil))}
var InventoryCaptureGroupResource = InventoryCaptureGroupDefinition{Definition: NewDefinition[apigen.InventoryCaptureGroupSpec]("homelab.io/v1alpha1", "/api/v1alpha1", "InventoryCaptureGroup", "inventory-capture-groups", "InventoryCaptureGroupStatus", []string(nil))}
var InventoryPublicationResource = InventoryPublicationDefinition{Definition: NewDefinition[apigen.InventoryPublicationSpec]("homelab.io/v1alpha1", "/api/v1alpha1", "InventoryPublication", "inventory-publications", "InventoryPublicationStatus", []string(nil))}
var MachineReportResource = MachineReportDefinition{Definition: NewDefinition[apigen.MachineReportSpec]("homelab.io/v1alpha1", "/api/v1alpha1", "MachineReport", "machine-reports", "", []string(nil))}
var MachineResource = MachineDefinition{Definition: NewDefinition[apigen.MachineSpec]("homelab.io/v1alpha1", "/api/v1alpha1", "Machine", "machines", "MachineStatus", []string(nil))}
var PipelineProviderResource = PipelineProviderDefinition{Definition: NewDefinition[apigen.PipelineProviderSpec]("homelab.io/v1alpha1", "/api/v1alpha1", "PipelineProvider", "pipeline-providers", "PipelineProviderStatus", []string(nil))}
var PipelineResource = PipelineDefinition{Definition: NewDefinition[apigen.PipelineSpec]("homelab.io/v1alpha1", "/api/v1alpha1", "Pipeline", "pipelines", "PipelineStatus", []string{"homelab.io/pipeline-cleanup"})}
var RouterResource = RouterDefinition{Definition: NewDefinition[apigen.RouterSpec]("homelab.io/v1alpha1", "/api/v1alpha1", "Router", "routers", "RouterStatus", []string(nil))}
var SecretStoreResource = SecretStoreDefinition{Definition: NewDefinition[apigen.SecretStoreSpec]("homelab.io/v1alpha1", "/api/v1alpha1", "SecretStore", "secret-stores", "", []string(nil))}
var SecretResource = SecretDefinition{Definition: NewDefinition[apigen.SecretSpec]("homelab.io/v1alpha1", "/api/v1alpha1", "Secret", "secrets", "SecretStatus", []string{"homelab.io/secret-cleanup"})}
var ServerResource = ServerDefinition{Definition: NewDefinition[apigen.ServerSpec]("homelab.io/v1alpha1", "/api/v1alpha1", "Server", "servers", "ServerStatus", []string(nil))}
var SSHKeyPairResource = SSHKeyPairDefinition{Definition: NewDefinition[apigen.SSHKeyPairSpec]("homelab.io/v1alpha1", "/api/v1alpha1", "SSHKeyPair", "ssh-key-pairs", "SSHKeyPairStatus", []string{"homelab.io/ssh-key-pair-cleanup"})}
var UsernamePasswordCredentialResource = UsernamePasswordCredentialDefinition{Definition: NewDefinition[apigen.UsernamePasswordCredentialSpec]("homelab.io/v1alpha1", "/api/v1alpha1", "UsernamePasswordCredential", "username-password-credentials", "UsernamePasswordCredentialStatus", []string{"homelab.io/username-password-cleanup"})}

var Definitions = []Definition{
	CommandsPipelineResource.Definition,
	DNSRecordResource.Definition,
	GitRepositoryResource.Definition,
	InventoryCaptureGroupResource.Definition,
	InventoryPublicationResource.Definition,
	MachineReportResource.Definition,
	MachineResource.Definition,
	PipelineProviderResource.Definition,
	PipelineResource.Definition,
	RouterResource.Definition,
	SecretStoreResource.Definition,
	SecretResource.Definition,
	ServerResource.Definition,
	SSHKeyPairResource.Definition,
	UsernamePasswordCredentialResource.Definition,
}
